// CS449 ASSIGNMENT 1 BlackJack
// T-TH 4-515
// Wonsun 

#include <stdio.h>
#include <string.h>

// Initializing all the functions in the program.
void print_dealer_hand(int Dealer_Hand[],int DH_Total_Cards);
int dealCard();
int sumCards(int hand[],int num_cards);
void print_player_hand(int Player_Hand[],int PH_Total_Cards);
void print_final_dealer_hand(int Dealer_Hand[],int DH_Total_Cards);

int main(void)
{
	// Seeds the random number generator 
	srand((unsigned int)time(NULL));
	
	// Will hold number generated by rand()
	int random_card;
	
	// While 0(false), the while loop continues. 
	int busted = 0;
	
	// Running totals of the player and dealer's sums
	int Dealer_Sum = 0;
	int Player_Sum = 0;
	
	// Will hold all of the cards in the user and dealer's hands
	int Dealer_Hand[10];
	int Player_Hand[10];
	
	// The total number of cards in the user and dealer's hands
	int DH_Total_Cards = 0;
	int PH_Total_Cards = 0;
	
	// Deals two cards to the player and two cards to the dealer
	Dealer_Hand[0] = dealCard();
	Dealer_Hand[1] = dealCard();
	DH_Total_Cards = 2;
	
	Player_Hand[0] = dealCard();
	Player_Hand[1] = dealCard();
	PH_Total_Cards = 2;
	
	// Make a character buffer of 99 chars plus null
	char playerResponse[100];
	
	char hit[] = "hit";
	char stand[] = "stand";
	
	Dealer_Sum = sumCards(Dealer_Hand, DH_Total_Cards);
	print_dealer_hand(Dealer_Hand,DH_Total_Cards);
		
	Player_Sum = sumCards(Player_Hand, PH_Total_Cards);
	print_player_hand(Player_Hand,PH_Total_Cards);
	printf("\nYour sum is equal to %d\n\n",Player_Sum);
	
	// Game will keep going until busted is 1(true)
	while( !busted )
	{
		if(Dealer_Sum == 21)
		{
			printf("\nDealer got BlackJack. Dealer wins!\n");
			busted = 1;
		}
		else
		{
			printf("Would you like to \"hit\" or \"stand\"?   ");
			scanf("%s", &playerResponse);
			printf("\n");
			
			int comparison_hit = strncmp(hit,playerResponse,3);
			int comparison_stand = strncmp(stand,playerResponse,5);
			
			// This while loop is for user input error checking. If the user types anything other than
			// 'hit' or 'stand', they'll be asked to re-enter their input until it is correct.
			while(comparison_hit != 0 && comparison_stand != 0)
			{
				printf("\nINPUT ERROR: Please enter 'hit' to take another card and 'stand' to keep your current cards.   ");
				scanf("%s", &playerResponse);
				printf("\n");
				
				comparison_hit = strncmp(hit,playerResponse,3);
				comparison_stand = strncmp(stand,playerResponse,5);
			}
			
			// If the player chose 'hit', they'll be dealt another card
			if(strncmp(hit,playerResponse,3) == 0)
			{
				Player_Hand[PH_Total_Cards] = dealCard();
				PH_Total_Cards = PH_Total_Cards + 1;
			}
			
			// If the dealer's sum is less than 17, then the dealer will be given another card.
			if(Dealer_Sum < 17)
			{
				Dealer_Hand[DH_Total_Cards] = dealCard();
				DH_Total_Cards = DH_Total_Cards + 1;
			}
					
			Dealer_Sum = sumCards(Dealer_Hand, DH_Total_Cards);
			print_dealer_hand(Dealer_Hand,DH_Total_Cards);
		
			Player_Sum = sumCards(Player_Hand, PH_Total_Cards);
			print_player_hand(Player_Hand,PH_Total_Cards);
			printf("\nYour sum is equal to %d\n\n",Player_Sum);
			
			
			// These are the win/lose conditions. If none of them are met, the while loop will happen again
			// and the player can get another card if they want.
			if(Player_Sum > 21)
			{
				print_final_dealer_hand(Dealer_Hand,DH_Total_Cards);
				printf("\nYou busted. Dealer wins!\n");
				busted = 1;
			}
			else if (Player_Sum < 21 &&  Dealer_Sum > 21)
			{
				printf("\nDealer busted. You win!\n");
				busted = 1;
			}
			else if(Dealer_Sum == 21)
			{
				print_final_dealer_hand(Dealer_Hand,DH_Total_Cards);
				printf("\nDealer got BlackJack. Dealer wins!\n");
				busted = 1;
			}
			else if(Player_Sum == 21 && Dealer_Sum < 21)
			{
				printf("\nYou got BlackJack. You win!\n");
				busted = 1;
			}
		}
	}
	return 0;
}


// Generates random card. Numbers 1 - 10 are
// the cards at face values, 1 being an Ace that can count 
// as a 1 or 11. Numbers 11-13 are Jack, Queen, and King, which
// also count for 10.
int dealCard()
{
	int random_card = (rand() % 13) + 1;
	
	if( random_card == 11 || random_card == 12 || random_card == 13)
	{
		random_card = 10;
	}
	
	return random_card;
}

// Prints the dealer's hand. The dealer's first card is printed as a ?,
// while the rest of the cards are printed normally 
void print_dealer_hand(int Dealer_Hand[],int DH_Total_Cards)
{
	int card = Dealer_Hand[DH_Total_Cards - 1];

	printf("The Dealer:\n");
	printf("? + %d",Dealer_Hand[1]);
	
	int i;
	for(i = 2; i < DH_Total_Cards; i = i + 1)
	{
		printf(" + ");
		printf("%d", Dealer_Hand[i]);
	}
	
	printf("\n\n");
}

// Prints the player's cards normally
void print_player_hand(int Player_Hand[],int PH_Total_Cards)
{

	printf("You:\n");
	printf("%d",Player_Hand[0]);
	
	int i;
	for(i = 1; i < PH_Total_Cards; i = i + 1)
	{
		printf(" + ");
		printf("%d",Player_Hand[i]);
	}
}

// Sums the cards in a player's hand. If there is an ace present, it is always counted
// as an 11 unless the total would be over 21, then it is counted as a 1
int sumCards(int hand[],int num_cards)
{
	int i, sum = 0, aceCount = 0;
	
	for(i = 0; i < num_cards; i = i + 1)
	{
		if(hand[i] == 1)
		{
			aceCount = aceCount + 1;
			sum = sum + 11;
		}
		else
		{
			sum = sum + hand[i];
		}
	}
	
	while(sum > 21 && aceCount > 0)
	{
		sum = sum - 10;
		aceCount = aceCount - 1;
	}
	
	return sum;	
}


// Prints the player's cards normally
void print_final_dealer_hand(int Dealer_Hand[],int DH_Total_Cards)
{

	printf("\nDealer's fully revealed hand:\n");
	printf("%d",Dealer_Hand[0]);
	
	int i;
	for(i = 1; i < DH_Total_Cards; i = i + 1)
	{
		printf(" + ");
		printf("%d",Dealer_Hand[i]);
	}
}
